### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by StixIt** [Soopyboo32/SoopyV2Forge#3]
![image](https://user-images.githubusercontent.com/112891222/189241636-83d16a44-7a3d-4579-b980-b3d2b63ccbc9.png)
IS there a known fix please respond asap.

**Comment by Soopyboo32** [comment]
wtf
never seen that before

does that still happen if u remove soopy?

**Comment by StixIt** [comment]
yes

**Comment by Soopyboo32** [comment]
So why did you make an issue here?
