### ISSUE TITLE
The glowing mushroom highlight is looking kinda wierd 

### ISSUE THREAD

**Issue by MRlonely3244** [Soopyboo32/SoopyV2Forge#4]
![Minecraft 1 8 9 08 01 2023 22_13_50](https://user-images.githubusercontent.com/122234316/211219363-7772f456-9ea7-484e-aea2-145dfda0a06f.png)

**Comment by Soopyboo32** [comment]
download optifine

**Comment by MRlonely3244** [comment]
ok thx but how on curseforge
